# Generated by Django 3.1.2 on 2020-12-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
