# Generated by Django 3.1.2 on 2020-12-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201204_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
