# Generated by Django 3.1.2 on 2020-12-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuringMachineDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_decisive', models.BinaryField(default=False)),
                ('instructions', models.TextField()),
                ('number_of_states', models.IntegerField()),
                ('alphabet', models.CharField(max_length=100)),
                ('starting_index', models.IntegerField(default=1)),
                ('empty_sign', models.CharField(default='#', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TuringSimulator.turingmachinedb')),
            ],
        ),
    ]
