# Generated by Django 3.1.2 on 2020-12-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0002_auto_20201203_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledb',
            name='example_steps_file',
            field=models.FileField(default='text_files/default.txt', upload_to='text_files'),
        ),
        migrations.AlterField(
            model_name='turingmachinedb',
            name='instructions',
            field=models.FileField(default='excel_files/default_excel.xlsx', upload_to='excel_files'),
        ),
    ]
