# Generated by Django 3.1.2 on 2020-12-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0003_auto_20201204_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turingmachinedb',
            name='is_decisive',
            field=models.BooleanField(default=False),
        ),
    ]
