# Generated by Django 3.1.2 on 2020-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0005_auto_20201206_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='turingmachinedb',
            name='initial_alphabet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turingmachinedb',
            name='initial_number_of_states',
            field=models.IntegerField(default=0),
        ),
    ]
