# Generated by Django 3.1.2 on 2020-12-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0006_auto_20201211_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledb',
            name='content',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
