# Generated by Django 3.1.2 on 2020-12-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0008_exampledb_example_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampledb',
            name='example_steps_file',
        ),
    ]
