# Generated by Django 3.1.2 on 2020-12-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0009_remove_exampledb_example_steps_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledb',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
