# Generated by Django 3.1.2 on 2020-12-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0011_turingmachinedb_excel_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledb',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TuringSimulator.turingmachinedb'),
        ),
    ]
