# Generated by Django 3.1.2 on 2020-12-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0012_auto_20201219_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampledb',
            name='last_value',
            field=models.CharField(default='None', max_length=5),
        ),
    ]
