# Generated by Django 3.1.2 on 2020-12-24 07:02

import TuringSimulator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0013_exampledb_last_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='turingmachinedb',
            name='aws_file_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='exampledb',
            name='example_steps',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='turingmachinedb',
            name='instructions',
            field=models.FileField(default='https://turing-machine-files-bucket.s3.us-east-2.amazonaws.com/excel_files/default_excel.xlsx', upload_to='excel_files', validators=[TuringSimulator.validators.validate_file_extension]),
        ),
    ]
