# Generated by Django 3.1.2 on 2020-12-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0014_auto_20201224_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='turingmachinedb',
            name='aws_file_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
