# Generated by Django 3.1.2 on 2020-12-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuringSimulator', '0015_turingmachinedb_aws_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='turingmachinedb',
            name='excel_filled',
            field=models.BooleanField(default=False),
        ),
    ]
